# Generated by Django 4.2 on 2023-04-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bedrooms', models.IntegerField(default=0)),
                ('sqft', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bathrooms', models.IntegerField(default=0)),
            ],
        ),
    ]
